GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user0@mail.ru user0000

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user0@mail.ru",
  "password": "user0000"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user0@mail.ru",
  "password": "user0000",
  "firstName": " asdad",
  "lastName": " asdad",
  "phone": " asdad",
  "role": "USER"
}

###
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic user@gmail.com password

###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user@gmail.com password

###
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user@gmail.com password

{
  "phone": "1111111111",
  "lastName": "Ivanov",
  "firstName": "Ivan"
}

###
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user0@mail.ru user0000

###
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic user0@mail.ru user0000

{
  "newPassword": "password0",
  "currentPassword": "user0000"
}

###
POST http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user0@mail.ru user0000

{
  "price": 123,
  "description": "123",
  "title": "123"
}
###2 user
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user@user.ru",
  "password": "123456789"
}




###6 все ads
GET  http://localhost:8080/ads

###7 все ads пользователя
GET  http://localhost:8080/ads/me

###8 info о пользователе
GET http://localhost:8080/users/me
