-- liquibase formatted sql

-- changeset alkor:1
CREATE TABLE ads (
                     pk INTEGER generated by default as identity PRIMARY KEY,
                     description VARCHAR(255) NOT NULL,
                     price INTEGER NOT NULL,
                     title VARCHAR(32) NOT NULL,
                     image_path VARCHAR(255),
                     author INTEGER,
                     CONSTRAINT price_constraint CHECK (price > 0 AND price < 10000000),
                     FOREIGN KEY(author) REFERENCES users(user_id)
);