-- liquibase formatted sql

-- changeset alkor:1
CREATE TABLE comments (
                          comment_id INTEGER generated by default as identity PRIMARY KEY,
                          comment_text VARCHAR(64) NOT NULL,
                          date_time_create BIGINT NOT NULL,
                          user_id INTEGER,
                          ads_id INTEGER,
                          FOREIGN KEY(user_id) REFERENCES users(user_id),
                          FOREIGN KEY(ads_id) REFERENCES ads(pk)
);